version: '3'
services:
  postgresdb:
    image: postgres
    restart: always
    container_name: postgresdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
  
  postgresadminer:
    image: adminer
    restart: always
